myvote/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'
urlpatterns = [
    path('', views.account_settings, name='overview'),
    path('view_profile/<int:user_id>', views.view_profile, name='view profile'),
    path('follow/<int:user_id>', views.follow_user, name='follow user'),
    path('unfollow/<int:user_id>', views.unfollow_user, name='unfollow user'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit_bio/', views.edit_bio, name='edit bio'),
    path('change_password/', views.change_password, name='change password'),
    path('change_email/', views.change_email, name='change email'),
    path('delete_account/', views.delete_account, name='delete account'),
]

myvote/myvote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('explore/recent/<int:user_id>', views.explore_recent_polls, name='explore recent polls'),
    path('explore/', views.explore_polls, name='explore polls'),
    path('create_poll/', views.create_poll, name='create poll'),
    path('vote_poll/<int:poll_id>/<int:option_id>', views.vote_poll, name='vote poll'),
    path('view_poll/<int:poll_id>/', views.view_poll, name='view poll'),
    path('delete_poll/<int:poll_id>/', views.delete_poll, name='delete poll'),
    path('search', views.search_all, name="search"),
    path('search/users/', views.search_users, name="search users"),
    path('search/polls/', views.search_polls, name="search polls"),

    path('account/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

myvote/templates/modules/footer.html
<footer>
  ©2018 MyVote
</footer>

myvote/templates/modules/header.html
<header class="main">
  <a href="{% url 'home' %}"><h1>MyVote</h1></a>

  <nav>
    <a href="{% url 'home' %}">home</a>
    <a href="{% url 'search' %}">search</a>
    <a href="{% url 'explore polls' %}">explore</a>
    {% if user.is_authenticated %}
      <a href="{% url 'create poll' %}">create</a>
      <a href="{% url 'account:view profile' user_id=user.id %}">my profile</a>
      <a href="{% url 'account:logout' %}">logout</a>
    {% else %}
      <a href="{% url 'account:signup' %}">sign up</a>
      <a href="{% url 'account:login' %}">login</a>
    {% endif %}
  </nav>
</header>

myvote/templates/modules/messages.html
{% if messages %}
<ul class="messages">
  {% for message in messages %}
    <li {% if message.tags %}class="{{ message.tags }}"{% endif %}>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

myvote/templates/modules/pagination_navigation.html
{% comment %}

  Pagination_Navigation

  This module provides a reusable set of navigation links for paginated views.

  Parameters (passed from parent template):
  - list (REQUIRED): the paginated list
  - url_param (optional): an optional parameter appended to the next/prev links url
  - prev_val (optional): an optional value for the previous button. Defaults to 'newer'
  - next_val (optional): an optional value for the next button. Defaults to 'older'

{% endcomment %}

<div class="pagination block_center text-center">
  <div class="previous-ctn">
    {% if list.has_previous %}
      <a href="?page={{ list.previous_page_number }}{% if url_param %}{{url_param}}{% endif %}" id="previous-page-button" class="link_button">
        {% if prev_val %}
          {{ prev_val }}
        {% else %}
          newer
        {% endif %}
      </a>
    {% endif %}
  </div>

  <div class="next-ctn">
    {% if list.has_next %}
      <a href="?page={{ list.next_page_number }}{% if url_param %}{{url_param}}{% endif %}" id="next-page-button" class="link_button">
        {% if next_val %}
          {{ next_val }}
        {% else %}
          older
        {% endif %}
      </a>
    {% endif %}
  </div>
</div>

myvote/templates/modules/poll_stream_item.html
{% load tz %}
<div class="ps_item">
  <header class="ps_item_header">
    <strong>
      <a href="{% url 'account:view profile' user_id=poll.owner.id %}">{{ poll.owner }}</a>
    </strong> created a new poll.
    {% timezone "America/Chicago" %}
    <span class="ps_item_header_timestamp">
      {{ poll.datetime|date:"SHORT_DATE_FORMAT" }}
      at
      {{ poll.datetime|date:"f a" }}
    </span>
    {% endtimezone %}
  </header>

  <section class="ps_item_content">
    <h3><a href="{% url 'view poll' poll_id=poll.id %}">{{ poll.name }}</a></h3>
    <p>
      {% if poll.description %}
        <i>{{ poll.description }}</i>
      {% else %}
        <i>This poll has no description.</i>
      {% endif %}
    </p>
    <hr />
    <div class="text-center">
      <a href="{% url 'view poll' poll_id=poll.id %}">Check it out! -></a>
    </div>
  </section>
</div>

myvote/templates/modules/poll_viewer.html
  <table class="text-center">
    <tr>
        <th colspan="2">
          <a href="{% url 'view poll' poll_id=poll.id %}">{{ poll.name }}</a>
        </th>
    </tr>
    <tr><th>Option</th><th>Votes</th></tr>
    {% for option in poll.options.all %}
    <tr>
      <td>{{ option.option_text }}</td>
      <td>{{ option.votes.count }}</td>
    </tr>
    {% endfor %}
  </table>


<!-- poll_viewer -->